apiVersion: v1
kind: Service
metadata:
  name: alphon-x4-service
spec:
  type: NodePort
  selector:
    app: alphon-x4-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080